default: &default
  adapter: mysql2
  encoding: utf8
  database: weavenote
  pool: 5
  username: root
  password:

development:
  <<: *default

test:
  <<: *default
  database: weavenote_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: root
  password: <%= ENV['DB_PASS'] %>
  socket: /run/mysqld/mysqld.sock
