default: &default
  adapter: mysql2
  encoding: utf8
  database: weavenote
  pool: 5
  username: root
  password:

development:
  <<: *default

test:
  <<: *default
  database: weavenote_test

production:
  <<: *default
  database: weavenote
  username: root
  password: Boobies!111
  socket: /run/mysqld/mysqld.sock
